#!/bin/bash

[[ "$(whoami)" != "root" ]] && echo "Please get root privileges to deploy system configuration." && exit 1

find \
	/etc/udev/rules.d \
	/etc/X11/xorg.conf.d \
	-type f -exec rm -v {} \;

cp -v etc/udev/rules.d/* /etc/udev/rules.d
cp -v etc/X11/xorg.conf.d/* /etc/X11/xorg.conf.d
