#!/bin/bash

sudo apt-get update && \
	sudo apt-get upgrade -y && \
	sudo apt-get dist-upgrade -y && \
	sudo apt-get install -y \
		adobe-flashplugin \
		enca \
		fping \
		git \
		hexchat \
		i2c-tools \
		iperf \
		lm-sensors \
		mc \
		network-manager-openvpn-gnome \
		powertop \
		python-pygments \
		rxvt-unicode \
		screen \
		shellcheck \
		skype \
		sysstat \
		subversion \
		xfonts-terminus \
		tcpdump \
		vlc \
		wireshark \
		zsh \
		|| exit 1
