#!/bin/sh

[[ "$(whoami)" != "root" ]] && echo "Please get root privileges to install packages." && exit 1

dnf install -yv \
	fping \
	gpsd-clients \
	hexchat \
	iotop \
	iperf \
	lm_sensors \
	mc \
	nano \
	screen \
	ShellCheck \
	smartmontools \
	sysstat \
	tcpdump \
	thunderbird \
	zsh
